# Generated by Django 5.2.7 on 2026-01-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_file',
            name='progress',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='case_file',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
