# Generated by Django 5.2.7 on 2026-01-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_case_file_progress_alter_case_file_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policestation',
            name='USER',
        ),
    ]
