# Generated by Django 5.2.7 on 2026-03-04 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_file',
            name='police',
        ),
        migrations.AddField(
            model_name='case_file',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.policestation'),
        ),
    ]
