# Generated by Django 5.2.7 on 2026-03-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_case_file_police_case_file_police_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing_person',
            name='photo',
            field=models.FileField(upload_to='missing'),
        ),
    ]
