# Generated by Django 5.2.7 on 2026-03-06 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_missing_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('confidence', models.CharField(max_length=255)),
                ('photo', models.FileField(upload_to='live_detections')),
                ('date', models.CharField(max_length=255)),
                ('status', models.CharField(default='detected', max_length=255)),
                ('Missing_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.missing_person')),
                ('criminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.criminal')),
            ],
        ),
    ]
