# Generated by Django 5.2.7 on 2026-03-07 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_live_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_upload',
            name='Missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.missing_person'),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='criminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.criminal'),
        ),
    ]
