# Generated by Django 5.2.7 on 2026-03-07 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_user_upload_missing_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_upload',
            name='Missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.missing_person'),
        ),
        migrations.AlterField(
            model_name='public_upload',
            name='criminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.criminal'),
        ),
    ]
