# Generated by Django 5.2.7 on 2026-03-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_live_detection_missing_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_detection',
            name='Missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.missing_person'),
        ),
        migrations.AlterField(
            model_name='live_detection',
            name='criminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.criminal'),
        ),
        migrations.AlterField(
            model_name='public_upload',
            name='Missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.missing_person'),
        ),
        migrations.AlterField(
            model_name='public_upload',
            name='criminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.criminal'),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='Missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.missing_person'),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='criminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.criminal'),
        ),
    ]
