# Generated by Django 5.2.7 on 2026-03-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_live_detection_missing_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_file',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
