# Generated by Django 5.2.7 on 2026-03-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_case_file_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_file',
            name='number',
        ),
    ]
