# Generated by Django 5.2.7 on 2026-03-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_case_file_gender_case_file_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_file',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
