# Generated by Django 5.2.7 on 2026-03-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_case_file_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_file',
            name='report',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
