# Generated by Django 5.2.7 on 2026-03-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_case_file_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_notification_check',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
